name: Viator
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  flutter_search_bar: ^3.0.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  flutter_launcher_icons: ^0.14.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/profile.png
    - assets/images/square-1.png
    - assets/images/square-2.png
    - assets/images/square-3.png
    - assets/images/square-4.png

    - assets/taj_mahal.jpg
    - assets/jaipur.jpg
    - assets/goa.jpg
    - assets/kerala.jpg
    - assets/rajasthan.jpg
    - assets/ladakh.jpg
    - assets/images.png
    - assets/mahakumbh.jpg
    - assets/avatar2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
