// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjUm-THdi1B-_8oBLsEIBkRPeiQFrq30',
    appId: '1:720526388343:web:f704c3e716535a8d55aa72',
    messagingSenderId: '720526388343',
    projectId: 'travelui-3b281',
    authDomain: 'travelui-3b281.firebaseapp.com',
    storageBucket: 'travelui-3b281.firebasestorage.app',
    measurementId: 'G-688EX949CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6n2hLLetIEJ2lPEABM2xnx6YK2eDDS8',
    appId: '1:720526388343:android:2f2b43b9e434f85a55aa72',
    messagingSenderId: '720526388343',
    projectId: 'travelui-3b281',
    storageBucket: 'travelui-3b281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyOCYbZvjHtVyIJ0-1SKD_bMIe15OGhow',
    appId: '1:720526388343:ios:d407d259a72ad0e855aa72',
    messagingSenderId: '720526388343',
    projectId: 'travelui-3b281',
    storageBucket: 'travelui-3b281.firebasestorage.app',
    iosBundleId: 'com.example.travelAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyOCYbZvjHtVyIJ0-1SKD_bMIe15OGhow',
    appId: '1:720526388343:ios:d407d259a72ad0e855aa72',
    messagingSenderId: '720526388343',
    projectId: 'travelui-3b281',
    storageBucket: 'travelui-3b281.firebasestorage.app',
    iosBundleId: 'com.example.travelAppUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChjUm-THdi1B-_8oBLsEIBkRPeiQFrq30',
    appId: '1:720526388343:web:c20245791449706b55aa72',
    messagingSenderId: '720526388343',
    projectId: 'travelui-3b281',
    authDomain: 'travelui-3b281.firebaseapp.com',
    storageBucket: 'travelui-3b281.firebasestorage.app',
    measurementId: 'G-P8GWRH27YM',
  );
}
